### PR TITLE
Refactor store and resource types into models package

### PR DESCRIPTION
**Pull request by dbrabera**
The original implementation had two types per API Resource, and those types were translated from and into the `store` package. I changed it to have a `models` package that is used all over the application. The mapping from models to MySQL tables is hidden under the `store.Store` api instead of being in the resource handlers. 

For proving that it works as expected, I extended the test suite with some basic integration tests for the MySQL store.

### CODE REVIEW

**Comment by ssimono** [comment]
The tests are actually altering the database, creating and updating features and environments forever thanks to config from the environment variables. This is bad, I didn't know that.

**Comment by ssimono** [comment]
I agree with the *models* package decision

**Comment by dbrabera** [comment]
I don't see a problem with the test wiping out the database on each run. It's the development database. Nothing valuable should be stored there. And it's a quite common behaviour in my opinion.

Even if I change it to create random data in each run, it will still mess up with the database. And we need integration tests for the `store` package. There is no other way to be sure that the database code works as is expected, than to actually running against a database.

**Comment by ssimono** [comment]
I think a proper solution would be to have a setting to indicate the databse in which you want the test to run. This way you can have a dedicated test database and are not forced to use the app-level connection settings

**Comment by dbrabera** [comment]
We can change the database name to always be `test`. Alternatively we can add a TEST prefix to the environment variables, Like `LAIKA_TEST_MYSQL_HOST`.

**Comment by ssimono** [comment]
:+1:

**Pull request merged**
